<template>
  <main>
    <NavBar></NavBar>
    <AboutHero></AboutHero>
    <AboutUs></AboutUs>
    <AboutHistory></AboutHistory>
    <AboutContacts></AboutContacts>
    <Footer></Footer>
  </main>
</template>
